export const boothPositions = [
  { id: 1, columnStart: 3, columnEnd: 4, rowStart: 1, rowEnd: 2 },
  { id: 2, columnStart: 16, columnEnd: 17, rowStart: 1, rowEnd: 2 },
  { id: 3, columnStart: 3, columnEnd: 5, rowStart: 2, rowEnd: 3 },
  { id: 4, columnStart: 15, columnEnd: 16, rowStart: 1, rowEnd: 3 },
  { id: 5, columnStart: 1, columnEnd: 2, rowStart: 2, rowEnd: 3 },
  { id: 6, columnStart: 2, columnEnd: 3, rowStart: 3, rowEnd: 4 },
  { id: 7, columnStart: 5, columnEnd: 6, rowStart: 3, rowEnd: 4 },
  { id: 8, columnStart: 6, columnEnd: 7, rowStart: 3, rowEnd: 4 },
  { id: 9, columnStart: 14, columnEnd: 15, rowStart: 2, rowEnd: 4 },
  { id: 10, columnStart: 13, columnEnd: 14, rowStart: 3, rowEnd: 4 },
  { id: 11, columnStart: 16, columnEnd: 18, rowStart: 3, rowEnd: 4 },
  { id: 12, columnStart: 17, columnEnd: 19, rowStart: 2, rowEnd: 3 },
  { id: 13, columnStart: 3, columnEnd: 4, rowStart: 4, rowEnd: 6 },
  { id: 14, columnStart: 15, columnEnd: 17, rowStart: 4, rowEnd: 5 },
  { id: 15, columnStart: 3, columnEnd: 4, rowStart: 5, rowEnd: 7 },
  { id: 16, columnStart: 15, columnEnd: 17, rowStart: 5, rowEnd: 6 },
  { id: 17, columnStart: 3, columnEnd: 4, rowStart: 7, rowEnd: 8 },
  { id: 18, columnStart: 15, columnEnd: 17, rowStart: 7, rowEnd: 8 },
  { id: 19, columnStart: 3, columnEnd: 4, rowStart: 8, rowEnd: 9 },
  { id: 20, columnStart: 15, columnEnd: 17, rowStart: 8, rowEnd: 9 },
  { id: 21, columnStart: 5, columnEnd: 7, rowStart: 9, rowEnd: 11 },
  { id: 22, columnStart: 13, columnEnd: 15, rowStart: 9, rowEnd: 11 },
  { id: 23, columnStart: 4, columnEnd: 6, rowStart: 10, rowEnd: 12 },
  { id: 24, columnStart: 14, columnEnd: 16, rowStart: 10, rowEnd: 12 },
];

export const manhaePositions = [
  { id: 1, columnStart: 1, columnEnd: 2, rowStart: 4, rowEnd: 6 },
  { id: 2, columnStart: 9, columnEnd: 11, rowStart: 2, rowEnd: 4 },
  { id: 3, columnStart: 11, columnEnd: 13, rowStart: 2, rowEnd: 4 },
  { id: 4, columnStart: 13, columnEnd: 14, rowStart: 2, rowEnd: 4 },
  { id: 5, columnStart: 15, columnEnd: 16, rowStart: 2, rowEnd: 4 },
  { id: 6, columnStart: 17, columnEnd: 18, rowStart: 3, rowEnd: 4 },
  { id: 7, columnStart: 18, columnEnd: 19, rowStart: 5, rowEnd: 6 },
  { id: 8, columnStart: 1, columnEnd: 2, rowStart: 6, rowEnd: 7 },
  { id: 9, columnStart: 1, columnEnd: 2, rowStart: 7, rowEnd: 8 },
  { id: 10, columnStart: 1, columnEnd: 3, rowStart: 8, rowEnd: 10 },
  { id: 11, columnStart: 2, columnEnd: 3, rowStart: 9, rowEnd: 11 },
  { id: 12, columnStart: 3, columnEnd: 4, rowStart: 11, rowEnd: 12 },
  { id: 13, columnStart: 4, columnEnd: 5, rowStart: 11, rowEnd: 13 },
  { id: 14, columnStart: 5, columnEnd: 6, rowStart: 11, rowEnd: 13 },
  { id: 15, columnStart: 6, columnEnd: 7, rowStart: 11, rowEnd: 13 },

  { id: 16, columnStart: 4, columnEnd: 5, rowStart: 4, rowEnd: 5 },
  { id: 17, columnStart: 5, columnEnd: 6, rowStart: 4, rowEnd: 5 },
  { id: 18, columnStart: 6, columnEnd: 7, rowStart: 4, rowEnd: 5 },
  { id: 19, columnStart: 7, columnEnd: 8, rowStart: 4, rowEnd: 5 },
  { id: 20, columnStart: 8, columnEnd: 10, rowStart: 4, rowEnd: 5 },
  { id: 21, columnStart: 9, columnEnd: 11, rowStart: 4, rowEnd: 5 },
  { id: 22, columnStart: 9, columnEnd: 11, rowStart: 5, rowEnd: 6 },
  { id: 23, columnStart: 9, columnEnd: 11, rowStart: 6, rowEnd: 7 },
  { id: 24, columnStart: 8, columnEnd: 9, rowStart: 5, rowEnd: 7 },
  { id: 25, columnStart: 7, columnEnd: 8, rowStart: 5, rowEnd: 7 },
  { id: 26, columnStart: 6, columnEnd: 7, rowStart: 5, rowEnd: 7 },
  { id: 27, columnStart: 5, columnEnd: 6, rowStart: 5, rowEnd: 7 },
  { id: 28, columnStart: 3, columnEnd: 5, rowStart: 5, rowEnd: 7 },
  { id: 29, columnStart: 3, columnEnd: 5, rowStart: 5, rowEnd: 6 },

  { id: 30, columnStart: 4, columnEnd: 5, rowStart: 8, rowEnd: 9 },
  { id: 31, columnStart: 4, columnEnd: 5, rowStart: 9, rowEnd: 10 },
  { id: 32, columnStart: 5, columnEnd: 6, rowStart: 9, rowEnd: 10 },
  { id: 33, columnStart: 6, columnEnd: 7, rowStart: 9, rowEnd: 10 },
  { id: 34, columnStart: 7, columnEnd: 8, rowStart: 9, rowEnd: 10 },
  { id: 35, columnStart: 8, columnEnd: 9, rowStart: 9, rowEnd: 10 },
  { id: 36, columnStart: 9, columnEnd: 11, rowStart: 9, rowEnd: 10 },
  { id: 37, columnStart: 9, columnEnd: 11, rowStart: 8, rowEnd: 9 },

  { id: 38, columnStart: 9, columnEnd: 11, rowStart: 7, rowEnd: 8 },
  { id: 39, columnStart: 8, columnEnd: 9, rowStart: 7, rowEnd: 8 },
  { id: 40, columnStart: 7, columnEnd: 8, rowStart: 7, rowEnd: 8 },
  { id: 41, columnStart: 6, columnEnd: 7, rowStart: 7, rowEnd: 8 },
  { id: 42, columnStart: 5, columnEnd: 6, rowStart: 7, rowEnd: 8 },
  { id: 43, columnStart: 4, columnEnd: 5, rowStart: 7, rowEnd: 8 },

  //맨 오른쪽 네모모
  { id: 44, columnStart: 11, columnEnd: 13, rowStart: 4, rowEnd: 5 },
  { id: 45, columnStart: 13, columnEnd: 14, rowStart: 4, rowEnd: 5 },
  { id: 46, columnStart: 14, columnEnd: 15, rowStart: 4, rowEnd: 5 },
  { id: 47, columnStart: 15, columnEnd: 17, rowStart: 4, rowEnd: 5 },

  { id: 48, columnStart: 15, columnEnd: 17, rowStart: 5, rowEnd: 6 },
  { id: 49, columnStart: 15, columnEnd: 17, rowStart: 6, rowEnd: 7 },
  { id: 50, columnStart: 15, columnEnd: 17, rowStart: 7, rowEnd: 8 },
  { id: 51, columnStart: 15, columnEnd: 17, rowStart: 8, rowEnd: 9 },
  { id: 52, columnStart: 15, columnEnd: 17, rowStart: 9, rowEnd: 10 },

  { id: 53, columnStart: 14, columnEnd: 15, rowStart: 9, rowEnd: 10 },
  { id: 54, columnStart: 13, columnEnd: 14, rowStart: 9, rowEnd: 10 },
  { id: 55, columnStart: 12, columnEnd: 13, rowStart: 9, rowEnd: 10 },

  { id: 56, columnStart: 12, columnEnd: 13, rowStart: 8, rowEnd: 9 },
  { id: 57, columnStart: 12, columnEnd: 13, rowStart: 7, rowEnd: 8 },
  { id: 58, columnStart: 12, columnEnd: 13, rowStart: 6, rowEnd: 7 },
  { id: 59, columnStart: 12, columnEnd: 13, rowStart: 5, rowEnd: 6 },
];

export const PLACENAME = {
  PALJEONGDO: "팔정도",
  MANHAE: "만해광장",
};
export const CATEGORYNAME = {
  BOOTH: "부스",
  FOODTRUCK: "푸드트럭",
};
